### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by Marcel-FR** [Marcel-FR/capstone-project#1]
## Value Proposition

- As a user,
- I want a Header on every page,
- So I can easily navigate through all the pages in the app.
​

## Description

![image](https://user-images.githubusercontent.com/121642717/222746856-c637e4ef-b234-4625-8a85-d592c06fdfbe.png)
​

## Acceptance Criteria

- [ ] The Header is a reusable component
- [ ] Clicking the back-arrow button will take you to the respective destination.
      ​

## Tasks

- [ ] Create a branch
- [ ] Create a reusable Header component
- [ ] Create functional buttons for the Header (like the back-arrow button)

**Comment by TuncAlt** [comment]
LGTM!
