### ISSUE TITLE
Bestiary-Information-Page-Styling

### ISSUE THREAD

**Issue by Marcel-FR** [Marcel-FR/capstone-project#13]
## Value Proposition

**As a** user,
**I want to** be able to read the text on the page easily,
**so that** so that I can understand the content and find the information I need quickly.

## Description

![image](https://user-images.githubusercontent.com/121642717/227080830-afd04a32-ed2f-4335-acc2-01931dc0779a.png)
​
Left: The page should have this format.
Right: This is the DnD Beyond monster statblock. I will take a lot of inspiration from this and follow the design for my app.

## Acceptance Criteria

- [ ] Clear and readable font.
- [ ] Consistent layout of the page.
- [ ] Design elements that help guide the user's attention to the most important information.
      ​

## Tasks

- [ ] Use StyledComponents to design the page.
- [ ] Use the DnD Beyond page as an orientation.​

**Comment by SarahWett** [comment]
Good one! :)
Pretty excited how your App will look like in the end!
