### ISSUE TITLE
Bestiary-Creation-Page

### ISSUE THREAD

**Issue by Marcel-FR** [Marcel-FR/capstone-project#15]
## Value Proposition

**As a** User,
**I want to** add my own monsters in the list,
**so that** I can have my own "homebrew" content.
​

## Description

Add an edit button to the Bestiary-List that routes me to a Monster-Creation-Page to create new monsters!
​

## Acceptance Criteria

- [ ] There is a new button in the Header of the Bestiary-List.
- [ ] Clicking on the button brings you to a new page, that lets you create a new monster.
      ​

## Tasks

- [ ] Import another SVG as an Icon for the button in the Header.
- [ ] Define the functionality of the button so that it redirects to the new monster creation page.
- [ ] Create a new page for the monster creation form, with all the necessary input fields and buttons.
