### ISSUE TITLE
NavButtons - Homescreen

### ISSUE THREAD

**Issue by Marcel-FR** [Marcel-FR/capstone-project#2]
## Value Proposition

- As a user,
- I want buttons on the homescreen,
- So that I can navigate through all sites of the app.
​

## Description

![image](https://user-images.githubusercontent.com/121642717/222713455-d7ee33fe-cbc5-4a00-8ee2-7408645f3387.png)
​

## Acceptance Criteria

- [ ] All buttons are displayed
- [ ] Clicking a button will take you to the respective destination.
      ​

## Tasks

- [ ] Create a branch
- [ ] Create the three buttons.
- [ ] Route the sites in next.js.

**Comment by MartinK1983** [comment]
good !

**Comment by pung-one** [comment]
fresh design!
