### ISSUE TITLE
Bestiary - List

### ISSUE THREAD

**Issue by Marcel-FR** [Marcel-FR/capstone-project#3]
## Value Proposition

- As a user,
- I want to be able to easily access a list of all the game's creatures in the bestiary,
- So that I can easily reference them while playing the game.
​

## Description

![image](https://user-images.githubusercontent.com/121642717/222995155-5eac9c8f-581c-4b97-b650-8c157f2459e1.png)
​

## Acceptance Criteria

- [ ] The app displays a list of all the game's creatures in the bestiary.
- [ ] The list is scrollable and easy to navigate.
- [ ] Users can click on a rule to view its details in a form.
      ​

## Tasks

- [ ] Add a Header that reads "Bestiary".
- [ ] Retrieve the list of all the game's creatures from the API.
- [ ] Implement pagination to prevent long lists from slowing down the app.
- [ ] Ensure that the list is user-friendly and easy to navigate.
- [ ] Allow users to click on a rule to open a form with details. (next US)
