### ISSUE TITLE
API Integration

### ISSUE THREAD

**Issue by Marcel-FR** [Marcel-FR/capstone-project#5]
## Value Proposition

- As a developer,
- I want to integrate an API for the game's rules, creatures and spells,
- So that I can easily use all the available information.
​

## Description

- Integration of an API that provides access to the game's rules, creatures and spells.
- Ensure that the API response is formatted correctly.
​

## Acceptance Criteria

- [ ] The app can fetch the game rules, creatures and spells data from the API.​

## Tasks

- [ ] Implement API requests in the app to fetch the data.
- [ ] Parse the API response and extract the necessary data.
- [ ] Map the data to the appropriate components in the app.
