### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by Marcel-FR** [Marcel-FR/capstone-project#6]
## Value Proposition

As a user, 
I want to be able to search for specific information in all the list, 
So that I can quickly find the details I need.
​

## Description

![image](https://user-images.githubusercontent.com/121642717/222997775-e0daaf1a-ef62-4ec8-9889-120070944acd.png)
​

## Acceptance Criteria

- [ ] The search bar appears at the top in the Header of the lists.
- [ ] Partial matches are allowed (e.g. searching for "aartuk" in the Bestiary should return "Aartuk Elder", "Aartuk Priest", etc.).
- [ ] The search is not case sensitive. (does not distinguish between uppercase and lowercase letters)
- [ ] The list updates in real-time as the user types.
      ​

## Tasks

- [ ] Create a new component for the search bar.
- [ ] Add the search bar component to all pages.
- [ ] Implement a search function that filters the list based on the user's input.
- [ ] Make the search function case-insensitive.
- [ ] Make the search function allow partial matches.
